//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.02.18 at 07:00:53 AM IST 
//


package com.adityo.springboot.soap.interfaces;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;



@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "employeeInfo", propOrder = {
    "employeeId",
    "name",
    "department",
    "phone",
    "address"
})
public class EmployeeInfo {

    protected long employeeId;
    @XmlElement(required = true)
    protected String name;
    @XmlElement(required = true)
    protected String department;
    @XmlElement(required = true)
    protected String phone;
    @XmlElement(required = true)
    protected String address;


    public long getEmployeeId() {
        return employeeId;
    }

    public void setEmployeeId(long value) {
        this.employeeId = value;
    }

    public String getName() {
        return name;
    }

    public void setName(String value) {
        this.name = value;
    }

    public String getDepartment() {
        return department;
    }

    public void setDepartment(String value) {
        this.department = value;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String value) {
        this.phone = value;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String value) {
        this.address = value;
    }

}
